services:
  discovery-server:
    build: 
      context: ./discovery-server/
      dockerfile: Dockerfile  
    image: discovery
    ports:
      - "8761:8761"
    networks:
      - movienet
  moviecatalog:
    build: 
      context: ./movie-catalog-service/
      dockerfile: Dockerfile
    image: moviecatalog
    ports:
      - "8081:8081"
    networks:
      - movienet
  movieinfo:
    build: 
      context: ./movie-info-service/
      dockerfile: Dockerfile
    image: movieinfo
    ports:
      - "8082:8082"
    networks:
      - movienet
  ratingservice:
    build: 
      context: ./ratings-data-service/
      dockerfile: Dockerfile
    image: ratingservice
    ports:
      - "8083:8083"
    networks:
      - movienet
networks:
  movienet:
    driver: bridge
